### ISSUE TITLE
Use Incognito Tab

### ISSUE THREAD

**Issue by eponsonby** [learn-co-curriculum/fewpjs-use-fetch#5]
Had to open up index.html in an incognito tab in order to see the game of thrones titles

**Comment by sgharms** [comment]
@eponsonby I don't see an `index.html` file in this repository. Could you please re-open on the correct repo?

**Comment by sgharms** [comment]
@eponsonby I think that this issue is meant to refer to:

https://github.com/learn-co-curriculum/fewpjs-fetch-lab

I just completed this lab successfully without using an Incognito tab:

![image](https://user-images.githubusercontent.com/50019/68213400-7e001000-ffa9-11e9-9e1d-a94373537560.png)

To understand where this is going off the rails, you might want to consider [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson).


Thanks! 💙
