### ISSUE TITLE
Routing off on the part of curriculum for me

### ISSUE THREAD

**Issue by mrandolph83** [learn-co-curriculum/fewpjs-use-fetch#9]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas
https://learning.flatironschool.com/courses/1882/pages/use-%60fetch-%60?module_item_id=259510

Add a link to the assignment in Canvas here.

## What should be changed?
I was following along these lessons linearly, and the curriculum jumped over the "Objects" section and straight into Fetch, and then after reading the lesson on Fetch, it jumped into the "Objects" lab, skipping over the lesson for Objects, which is quite a long and important one. I was quite lost with the Objects lab and kept feeling like there was a piece missing, as there didn't seem to be a lot or problems with it on Slack. I don't know if it's a browser/cache issue on my end or a routing issue on your end, but someone should look into it. I was quite lost and wondering why it seemed like I would be thrown into a lab with concepts that hadn't been touched on yet.

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

**Comment by ihollander** [comment]
Hi @mrandolph83 , thanks for flagging this issue! I've updated your Canvas course so the next buttons link to the correct pages within the Communicating with the Server module. Unfortunately this behavior is hard to spot, since the Next button is intended to work by progressing to the next page based on how they are ordered within the module, but there seems to be a bug in Canvas where this is not always the case, and the Next button can be unreliable. It may help to view the list of pages from the [course homepage](https://learning.flatironschool.com/courses/1882) and open new pages in their own tab instead of using the Next button.
